development:
  adapter: postgresql
  encoding: utf8
  database: trailblaze_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: trailblaze_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: trailblaze_production
  pool: 5
  username:
  password:
